name = "RODEConvergence"
uuid = "3e0417cb-ed7b-43e1-a831-672d2fe3e1aa"
authors = ["Ricardo M. S. Rosa <rmsrosa@gmail.com>"]
version = "1.0.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
